---
- name: Creating gnome.d directory from DConf
  file:
    path: /etc/dconf/db/gnome.d
    state: directory
    mode: 0755

- name: Configuring GNOME
  template:
    src: gnome.d/00-gnome.j2
    dest: /etc/dconf/db/gnome.d/00-gnome.j2
    mode: 0644

- name: Configuring DConf
  lineinfile:
    path: /etc/dconf/profile/user
    line: "{{ item }}"
    create: yes
    mode: 0644
  with_items:
    - "user-db:user"
    - "system-db:gnome"
  become: yes

